### PR TITLE
Add observer impl - instead of using own SpanData interface, it now u…

### PR DESCRIPTION
**Pull request by objectiser**
…ses the Observer's version, so this will affect any metric reporters

Created this PR as an example for how the Observer API could be used. Requires more tests.

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Could you review this please? Its an update to remove the internal tracer wrapper and instead switch over to using the observer (and its tracer wrapper). There were also some formatting changes.

Also added a slight update, to enable multiple `MetricsReporters` to be specified - to support different sets of labels.

**Comment by objectiser** [comment]
Tested against example: https://github.com/objectiser/opentracing-prometheus-example

**Review by jpkrohling — APPROVED** [review]
LGTM

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
